# Build stage
FROM node:22-alpine AS BUILD

WORKDIR /app

COPY package.json package-lock.json .
RUN npm ci

COPY . .
RUN npm run build

# Prod stage
FROM node:22-alpine AS PROD

WORKDIR /app

COPY package.json package-lock.json .
RUN npm ci --production

COPY --from=BUILD /app/dist ./dist

CMD ["npm", "run", "start"]
