services:
  app_dev:
    container_name: webapp_dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app # mount local code for hot reload
      - /app/node_modules # DISALLOW host node_modules from overwrite docker node_modules
    ports:
      - "5173:5173"
    env_file:
      - .env.development
